"""migrate schema from 0.9.10 to 0.9.11

Revision ID: 0a84c302c248
Revises: 47ec461dd69b
Create Date: 2025-03-18 14:01:07.233090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a84c302c248'
down_revision: Union[str, None] = '72d2efa4027d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rainfall_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('provider_admin1_name', sa.String(length=512), nullable=False),
    sa.Column('provider_admin2_name', sa.String(length=512), nullable=False),
    sa.Column('provider_admin1_code', sa.String(length=512), nullable=False),
    sa.Column('provider_admin2_code', sa.String(length=512), nullable=False),
    sa.Column('aggregation_period', sa.Enum('dekad', '1-month', '3-month', name='aggregationperiod'), nullable=False),
    sa.Column('rainfall', sa.Numeric(), nullable=False),
    sa.Column('rainfall_long_term_average', sa.Numeric(), nullable=False),
    sa.Column('rainfall_anomaly_pct', sa.Numeric(), nullable=False),
    sa.Column('number_pixels', sa.Integer(), nullable=False),
    sa.Column('version', sa.Enum('final', 'forecast', 'preliminary', name='version'), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=False),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('has_hrp', sa.Boolean(), nullable=False),
    sa.Column('in_gho', sa.Boolean(), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.Column('admin_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin2_ref', 'provider_admin1_name', 'provider_admin2_name', 'provider_admin1_code', 'provider_admin2_code', 'aggregation_period', 'version', 'reference_period_start')
    )
    op.create_index(op.f('ix_rainfall_vat_admin1_code'), 'rainfall_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_rainfall_vat_admin1_name'), 'rainfall_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_rainfall_vat_admin2_code'), 'rainfall_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_rainfall_vat_admin2_name'), 'rainfall_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_rainfall_vat_admin_level'), 'rainfall_vat', ['admin_level'], unique=False)
    op.create_index(op.f('ix_rainfall_vat_location_code'), 'rainfall_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_rainfall_vat_location_name'), 'rainfall_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_rainfall_vat_reference_period_end'), 'rainfall_vat', ['reference_period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rainfall_vat_reference_period_end'), table_name='rainfall_vat')
    op.drop_index(op.f('ix_rainfall_vat_location_name'), table_name='rainfall_vat')
    op.drop_index(op.f('ix_rainfall_vat_location_code'), table_name='rainfall_vat')
    op.drop_index(op.f('ix_rainfall_vat_admin_level'), table_name='rainfall_vat')
    op.drop_index(op.f('ix_rainfall_vat_admin2_name'), table_name='rainfall_vat')
    op.drop_index(op.f('ix_rainfall_vat_admin2_code'), table_name='rainfall_vat')
    op.drop_index(op.f('ix_rainfall_vat_admin1_name'), table_name='rainfall_vat')
    op.drop_index(op.f('ix_rainfall_vat_admin1_code'), table_name='rainfall_vat')
    op.drop_table('rainfall_vat')
    # ### end Alembic commands ###
