"""Migrate schema from 0.9.3 to 0.9.6

Revision ID: 2f625bfc45a7
Revises: 1aea8e675afa
Create Date: 2024-12-08 22:26:22.692215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f625bfc45a7'
down_revision: Union[str, None] = '1aea8e675afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Delete table because we want to recreate it without the primary key and with indeces instead
    op.drop_table("data_availability_vat")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_availability_vat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('subcategory', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin_level', sa.Integer(), nullable=False),
    sa.Column('hapi_updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_availability_vat_admin1_code'), 'data_availability_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_admin1_name'), 'data_availability_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_admin2_code'), 'data_availability_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_admin2_name'), 'data_availability_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_admin_level'), 'data_availability_vat', ['admin_level'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_category'), 'data_availability_vat', ['category'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_hapi_updated_date'), 'data_availability_vat', ['hapi_updated_date'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_location_code'), 'data_availability_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_location_name'), 'data_availability_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_data_availability_vat_subcategory'), 'data_availability_vat', ['subcategory'], unique=False)

    op.add_column('conflict_event_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_conflict_event_vat_admin_level'), 'conflict_event_vat', ['admin_level'], unique=False)
    op.alter_column('conflict_event_vat', 'admin_level', server_default=None)

    op.add_column('food_price_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_food_price_vat_admin_level'), 'food_price_vat', ['admin_level'], unique=False)
    op.alter_column('food_price_vat', 'admin_level', server_default=None)

    op.add_column('food_security_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_food_security_vat_admin_level'), 'food_security_vat', ['admin_level'], unique=False)
    op.alter_column('food_security_vat', 'admin_level', server_default=None)

    op.add_column('humanitarian_needs_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_humanitarian_needs_vat_admin_level'), 'humanitarian_needs_vat', ['admin_level'], unique=False)
    op.alter_column('humanitarian_needs_vat', 'admin_level', server_default=None)

    op.add_column('idps_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_idps_vat_admin_level'), 'idps_vat', ['admin_level'], unique=False)
    op.alter_column('idps_vat', 'admin_level', server_default=None)

    op.add_column('operational_presence_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_operational_presence_vat_admin_level'), 'operational_presence_vat', ['admin_level'], unique=False)
    op.alter_column('operational_presence_vat', 'admin_level', server_default=None)

    op.add_column('population_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_population_vat_admin_level'), 'population_vat', ['admin_level'], unique=False)
    op.alter_column('population_vat', 'admin_level', server_default=None)

    op.add_column('poverty_rate_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_poverty_rate_vat_admin_level'), 'poverty_rate_vat', ['admin_level'], unique=False)
    op.alter_column('poverty_rate_vat', 'admin_level', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poverty_rate_vat_admin_level'), table_name='poverty_rate_vat')
    op.drop_column('poverty_rate_vat', 'admin_level')
    op.drop_index(op.f('ix_population_vat_admin_level'), table_name='population_vat')
    op.drop_column('population_vat', 'admin_level')
    op.drop_index(op.f('ix_operational_presence_vat_admin_level'), table_name='operational_presence_vat')
    op.drop_column('operational_presence_vat', 'admin_level')
    op.drop_index(op.f('ix_idps_vat_admin_level'), table_name='idps_vat')
    op.drop_column('idps_vat', 'admin_level')
    op.drop_index(op.f('ix_humanitarian_needs_vat_admin_level'), table_name='humanitarian_needs_vat')
    op.drop_column('humanitarian_needs_vat', 'admin_level')
    op.drop_index(op.f('ix_food_security_vat_admin_level'), table_name='food_security_vat')
    op.drop_column('food_security_vat', 'admin_level')
    op.drop_index(op.f('ix_food_price_vat_admin_level'), table_name='food_price_vat')
    op.drop_column('food_price_vat', 'admin_level')
    op.drop_index(op.f('ix_conflict_event_vat_admin_level'), table_name='conflict_event_vat')
    op.drop_column('conflict_event_vat', 'admin_level')

    op.drop_table('data_availability_vat')
    op.create_table('data_availability_vat',
    sa.Column('category', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('location_code', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('admin1_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('admin1_code', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('admin2_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('admin2_code', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('hapi_updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category', 'subcategory', 'location_name', 'location_code', 'admin1_name', 'admin1_code', 'admin2_name', 'admin2_code', name='data_availability_vat_pkey')
    )
    op.create_index('ix_data_availability_vat_hapi_updated_date', 'data_availability_vat', ['hapi_updated_date'], unique=False)
    # ### end Alembic commands ###
