"""migrate schema from 0.9.9 to 0.9.10

Revision ID: 47ec461dd69b
Revises: 71a8a3d98933
Create Date: 2025-02-27 09:19:06.117585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47ec461dd69b'
down_revision: Union[str, None] = '71a8a3d98933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin1_vat', 'reference_period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('conflict_event_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('food_price_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('food_security_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('funding_vat', 'appeal_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('funding_vat', 'requirements_usd',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('funding_vat', 'funding_pct',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('funding_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_funding_vat_reference_period_start', table_name='funding_vat')
    op.create_index(op.f('ix_funding_vat_reference_period_end'), 'funding_vat', ['reference_period_end'], unique=False)
    op.alter_column('humanitarian_needs_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('idps_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('location_vat', 'reference_period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('national_risk_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('population_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('poverty_rate_vat', 'intensity_of_deprivation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('poverty_rate_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('refugees_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('returnees_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('returnees_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('refugees_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('poverty_rate_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('poverty_rate_vat', 'intensity_of_deprivation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('population_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('national_risk_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('location_vat', 'reference_period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('idps_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('humanitarian_needs_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_funding_vat_reference_period_end'), table_name='funding_vat')
    op.create_index('ix_funding_vat_reference_period_start', 'funding_vat', ['reference_period_start'], unique=False)
    op.alter_column('funding_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('funding_vat', 'funding_pct',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('funding_vat', 'requirements_usd',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('funding_vat', 'appeal_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('food_security_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('food_price_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('conflict_event_vat', 'reference_period_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('admin1_vat', 'reference_period_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
