"""migrate schema from 0.9.6 to 0.9.9

Revision ID: 71a8a3d98933
Revises: 2f625bfc45a7
Create Date: 2025-02-25 15:46:19.104599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a8a3d98933'
down_revision: Union[str, None] = '2f625bfc45a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wfp_market_vat', sa.Column('admin_level', sa.Integer(), nullable=False, server_default='-1'))
    op.create_index(op.f('ix_wfp_market_vat_admin_level'), 'wfp_market_vat', ['admin_level'], unique=False)
    op.alter_column('wfp_market_vat', 'admin_level', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wfp_market_vat_admin_level'), table_name='wfp_market_vat')
    op.drop_column('wfp_market_vat', 'admin_level')
    # ### end Alembic commands ###
