"""from schema 0.8.12 to 0.8.14

Revision ID: 844d4f958348
Revises: a3d008e15c82
Create Date: 2024-07-24 16:40:02.259167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844d4f958348'
down_revision: Union[str, None] = 'a3d008e15c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin1_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('admin1_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('admin2_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('admin2_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('conflict_event_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('conflict_event_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('food_price_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('food_price_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('food_security_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('food_security_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('funding_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('funding_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('humanitarian_needs_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('humanitarian_needs_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('location_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('location_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('national_risk_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('national_risk_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('operational_presence_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('operational_presence_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('population_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('population_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('poverty_rate_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('poverty_rate_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    op.add_column('refugees_vat', sa.Column('origin_has_hrp', sa.Boolean(), nullable=False))
    op.add_column('refugees_vat', sa.Column('origin_in_gho', sa.Boolean(), nullable=False))
    op.add_column('refugees_vat', sa.Column('asylum_has_hrp', sa.Boolean(), nullable=False))
    op.add_column('refugees_vat', sa.Column('asylum_in_gho', sa.Boolean(), nullable=False))
    op.add_column('wfp_market_vat', sa.Column('has_hrp', sa.Boolean(), nullable=False))
    op.add_column('wfp_market_vat', sa.Column('in_gho', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wfp_market_vat', 'in_gho')
    op.drop_column('wfp_market_vat', 'has_hrp')
    op.drop_column('refugees_vat', 'asylum_in_gho')
    op.drop_column('refugees_vat', 'asylum_has_hrp')
    op.drop_column('refugees_vat', 'origin_in_gho')
    op.drop_column('refugees_vat', 'origin_has_hrp')
    op.drop_column('poverty_rate_vat', 'in_gho')
    op.drop_column('poverty_rate_vat', 'has_hrp')
    op.drop_column('population_vat', 'in_gho')
    op.drop_column('population_vat', 'has_hrp')
    op.drop_column('operational_presence_vat', 'in_gho')
    op.drop_column('operational_presence_vat', 'has_hrp')
    op.drop_column('national_risk_vat', 'in_gho')
    op.drop_column('national_risk_vat', 'has_hrp')
    op.drop_column('location_vat', 'in_gho')
    op.drop_column('location_vat', 'has_hrp')
    op.drop_column('humanitarian_needs_vat', 'in_gho')
    op.drop_column('humanitarian_needs_vat', 'has_hrp')
    op.drop_column('funding_vat', 'in_gho')
    op.drop_column('funding_vat', 'has_hrp')
    op.drop_column('food_security_vat', 'in_gho')
    op.drop_column('food_security_vat', 'has_hrp')
    op.drop_column('food_price_vat', 'in_gho')
    op.drop_column('food_price_vat', 'has_hrp')
    op.drop_column('conflict_event_vat', 'in_gho')
    op.drop_column('conflict_event_vat', 'has_hrp')
    op.drop_column('admin2_vat', 'in_gho')
    op.drop_column('admin2_vat', 'has_hrp')
    op.drop_column('admin1_vat', 'in_gho')
    op.drop_column('admin1_vat', 'has_hrp')
    # ### end Alembic commands ###
