"""Init tables

Revision ID: a3d008e15c82
Revises: 
Create Date: 2024-06-12 14:50:10.726685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d008e15c82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin1_vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('from_cods', sa.Boolean(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin1_vat_code'), 'admin1_vat', ['code'], unique=False)
    op.create_index(op.f('ix_admin1_vat_location_code'), 'admin1_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_admin1_vat_location_name'), 'admin1_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_admin1_vat_name'), 'admin1_vat', ['name'], unique=False)
    op.create_index(op.f('ix_admin1_vat_reference_period_end'), 'admin1_vat', ['reference_period_end'], unique=False)
    op.create_index(op.f('ix_admin1_vat_reference_period_start'), 'admin1_vat', ['reference_period_start'], unique=False)
    op.create_table('admin2_vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('from_cods', sa.Boolean(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=True),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin2_vat_code'), 'admin2_vat', ['code'], unique=False)
    op.create_index(op.f('ix_admin2_vat_location_code'), 'admin2_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_admin2_vat_location_name'), 'admin2_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_admin2_vat_name'), 'admin2_vat', ['name'], unique=False)
    op.create_index(op.f('ix_admin2_vat_reference_period_end'), 'admin2_vat', ['reference_period_end'], unique=False)
    op.create_index(op.f('ix_admin2_vat_reference_period_start'), 'admin2_vat', ['reference_period_start'], unique=False)
    op.create_table('conflict_event_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('civilian_targeting', 'demonstration', 'political_violence', name='eventtype'), nullable=False),
    sa.Column('events', sa.Integer(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin2_ref', 'event_type', 'reference_period_start')
    )
    op.create_index(op.f('ix_conflict_event_vat_admin1_code'), 'conflict_event_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_admin1_name'), 'conflict_event_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_admin2_code'), 'conflict_event_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_admin2_name'), 'conflict_event_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_events'), 'conflict_event_vat', ['events'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_fatalities'), 'conflict_event_vat', ['fatalities'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_location_code'), 'conflict_event_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_location_name'), 'conflict_event_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_conflict_event_vat_reference_period_end'), 'conflict_event_vat', ['reference_period_end'], unique=False)
    op.create_table('currency_vat',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_currency_vat_name'), 'currency_vat', ['name'], unique=False)
    op.create_table('dataset_vat',
    sa.Column('hdx_id', sa.String(length=36), nullable=False),
    sa.Column('hdx_stub', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('hdx_provider_stub', sa.String(length=128), nullable=False),
    sa.Column('hdx_provider_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('hdx_id')
    )
    op.create_index(op.f('ix_dataset_vat_hdx_provider_name'), 'dataset_vat', ['hdx_provider_name'], unique=False)
    op.create_index(op.f('ix_dataset_vat_hdx_provider_stub'), 'dataset_vat', ['hdx_provider_stub'], unique=False)
    op.create_index(op.f('ix_dataset_vat_hdx_stub'), 'dataset_vat', ['hdx_stub'], unique=False)
    op.create_table('food_price_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('market_code', sa.String(length=32), nullable=False),
    sa.Column('commodity_code', sa.String(length=32), nullable=False),
    sa.Column('currency_code', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('price_flag', sa.Enum('actual', 'aggregate', 'actual,aggregate', name='priceflag'), nullable=False),
    sa.Column('price_type', sa.Enum('Farm Gate', 'Retail', 'Wholesale', name='pricetype'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('market_name', sa.String(length=512), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('commodity_category', sa.Enum('cereals and tubers', 'meat, fish and eggs', 'milk and dairy', 'miscellaneous food', 'non-food', 'oil and fats', 'pulses and nuts', 'vegetables and fruits', name='commoditycategory'), nullable=False),
    sa.Column('commodity_name', sa.String(length=512), nullable=False),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('market_code', 'commodity_code', 'unit', 'price_flag', 'price_type', 'reference_period_start')
    )
    op.create_index(op.f('ix_food_price_vat_admin1_code'), 'food_price_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_food_price_vat_admin1_name'), 'food_price_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_food_price_vat_admin2_code'), 'food_price_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_food_price_vat_admin2_name'), 'food_price_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_food_price_vat_commodity_name'), 'food_price_vat', ['commodity_name'], unique=False)
    op.create_index(op.f('ix_food_price_vat_currency_code'), 'food_price_vat', ['currency_code'], unique=False)
    op.create_index(op.f('ix_food_price_vat_lat'), 'food_price_vat', ['lat'], unique=False)
    op.create_index(op.f('ix_food_price_vat_location_code'), 'food_price_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_food_price_vat_location_name'), 'food_price_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_food_price_vat_lon'), 'food_price_vat', ['lon'], unique=False)
    op.create_index(op.f('ix_food_price_vat_market_name'), 'food_price_vat', ['market_name'], unique=False)
    op.create_index(op.f('ix_food_price_vat_reference_period_end'), 'food_price_vat', ['reference_period_end'], unique=False)
    op.create_table('food_security_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('ipc_phase', sa.Enum('1', '2', '3', '4', '5', '3+', 'all', name='ipcphase'), nullable=False),
    sa.Column('ipc_type', sa.Enum('current', 'first projection', 'second projection', name='ipctype'), nullable=False),
    sa.Column('population_in_phase', sa.Integer(), nullable=False),
    sa.Column('population_fraction_in_phase', sa.Numeric(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin2_ref', 'ipc_phase', 'ipc_type', 'reference_period_start')
    )
    op.create_index(op.f('ix_food_security_vat_admin1_code'), 'food_security_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_food_security_vat_admin1_name'), 'food_security_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_food_security_vat_admin2_code'), 'food_security_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_food_security_vat_admin2_name'), 'food_security_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_food_security_vat_location_code'), 'food_security_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_food_security_vat_location_name'), 'food_security_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_food_security_vat_population_fraction_in_phase'), 'food_security_vat', ['population_fraction_in_phase'], unique=False)
    op.create_index(op.f('ix_food_security_vat_population_in_phase'), 'food_security_vat', ['population_in_phase'], unique=False)
    op.create_index(op.f('ix_food_security_vat_reference_period_end'), 'food_security_vat', ['reference_period_end'], unique=False)
    op.create_table('funding_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('appeal_code', sa.String(length=32), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('appeal_name', sa.String(length=256), nullable=False),
    sa.Column('appeal_type', sa.String(length=32), nullable=False),
    sa.Column('requirements_usd', sa.Numeric(), nullable=False),
    sa.Column('funding_usd', sa.Numeric(), nullable=False),
    sa.Column('funding_pct', sa.Numeric(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('appeal_code', 'location_ref')
    )
    op.create_index(op.f('ix_funding_vat_funding_pct'), 'funding_vat', ['funding_pct'], unique=False)
    op.create_index(op.f('ix_funding_vat_funding_usd'), 'funding_vat', ['funding_usd'], unique=False)
    op.create_index(op.f('ix_funding_vat_location_code'), 'funding_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_funding_vat_location_name'), 'funding_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_funding_vat_reference_period_start'), 'funding_vat', ['reference_period_start'], unique=False)
    op.create_index(op.f('ix_funding_vat_requirements_usd'), 'funding_vat', ['requirements_usd'], unique=False)
    op.create_table('humanitarian_needs_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('f', 'm', 'x', 'u', 'o', 'all', name='gender'), nullable=False),
    sa.Column('age_range', sa.String(length=32), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('population_group', sa.Enum('REF', 'ROC', 'ASY', 'OIP', 'IDP', 'IOC', 'STA', 'OOC', 'HST', 'RET', 'RST', 'NAT', 'RDP', 'RRI', 'all', name='populationgroup'), nullable=False),
    sa.Column('population_status', sa.Enum('AFF', 'INN', 'TGT', 'REA', 'all', name='populationstatus'), nullable=False),
    sa.Column('disabled_marker', sa.Enum('y', 'n', 'all', name='disabledmarker'), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('sector_name', sa.String(length=512), nullable=False),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin2_ref', 'gender', 'age_range', 'sector_code', 'population_group', 'population_status', 'disabled_marker', 'reference_period_start')
    )
    op.create_index(op.f('ix_humanitarian_needs_vat_admin1_code'), 'humanitarian_needs_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_admin1_name'), 'humanitarian_needs_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_admin2_code'), 'humanitarian_needs_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_admin2_name'), 'humanitarian_needs_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_location_code'), 'humanitarian_needs_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_location_name'), 'humanitarian_needs_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_max_age'), 'humanitarian_needs_vat', ['max_age'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_min_age'), 'humanitarian_needs_vat', ['min_age'], unique=False)
    op.create_index(op.f('ix_humanitarian_needs_vat_reference_period_end'), 'humanitarian_needs_vat', ['reference_period_end'], unique=False)
    op.create_table('location_vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('from_cods', sa.Boolean(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_vat_code'), 'location_vat', ['code'], unique=False)
    op.create_index(op.f('ix_location_vat_name'), 'location_vat', ['name'], unique=False)
    op.create_index(op.f('ix_location_vat_reference_period_end'), 'location_vat', ['reference_period_end'], unique=False)
    op.create_index(op.f('ix_location_vat_reference_period_start'), 'location_vat', ['reference_period_start'], unique=False)
    op.create_table('national_risk_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('risk_class', sa.Enum('1', '2', '3', '4', '5', name='riskclass'), nullable=False),
    sa.Column('global_rank', sa.Integer(), nullable=False),
    sa.Column('overall_risk', sa.Numeric(), nullable=False),
    sa.Column('hazard_exposure_risk', sa.Numeric(), nullable=False),
    sa.Column('vulnerability_risk', sa.Numeric(), nullable=False),
    sa.Column('coping_capacity_risk', sa.Numeric(), nullable=False),
    sa.Column('meta_missing_indicators_pct', sa.Numeric(), nullable=True),
    sa.Column('meta_avg_recentness_years', sa.Numeric(), nullable=True),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('location_ref', 'reference_period_start')
    )
    op.create_index(op.f('ix_national_risk_vat_location_code'), 'national_risk_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_national_risk_vat_location_name'), 'national_risk_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_national_risk_vat_reference_period_end'), 'national_risk_vat', ['reference_period_end'], unique=False)
    op.create_table('operational_presence_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('org_acronym', sa.String(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('org_type_code', sa.String(length=32), nullable=False),
    sa.Column('org_type_description', sa.String(length=512), nullable=False),
    sa.Column('sector_name', sa.String(length=512), nullable=False),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin2_ref', 'org_acronym', 'org_name', 'sector_code', 'reference_period_start')
    )
    op.create_index(op.f('ix_operational_presence_vat_admin1_code'), 'operational_presence_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_operational_presence_vat_admin1_name'), 'operational_presence_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_operational_presence_vat_admin2_code'), 'operational_presence_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_operational_presence_vat_admin2_name'), 'operational_presence_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_operational_presence_vat_location_code'), 'operational_presence_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_operational_presence_vat_location_name'), 'operational_presence_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_operational_presence_vat_org_type_description'), 'operational_presence_vat', ['org_type_description'], unique=False)
    op.create_index(op.f('ix_operational_presence_vat_reference_period_end'), 'operational_presence_vat', ['reference_period_end'], unique=False)
    op.create_table('org_type_vat',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_org_type_vat_description'), 'org_type_vat', ['description'], unique=False)
    op.create_table('org_vat',
    sa.Column('acronym', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('org_type_code', sa.String(length=32), nullable=True),
    sa.Column('org_type_description', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('acronym', 'name')
    )
    op.create_index(op.f('ix_org_vat_org_type_code'), 'org_vat', ['org_type_code'], unique=False)
    op.create_index(op.f('ix_org_vat_org_type_description'), 'org_vat', ['org_type_description'], unique=False)
    op.create_table('patch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_sequence_number', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=48), nullable=False),
    sa.Column('commit_date', sa.DateTime(), nullable=False),
    sa.Column('patch_path', sa.String(length=512), nullable=False),
    sa.Column('patch_permalink_url', sa.String(length=1024), nullable=False),
    sa.Column('patch_target', sa.String(length=128), nullable=False),
    sa.Column('patch_hash', sa.String(length=48), nullable=False),
    sa.Column('state', sa.Enum('discovered', 'executed', 'failed', 'canceled', name='stateenum'), nullable=False),
    sa.Column('execution_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_execution_date'), 'patch', ['execution_date'], unique=False)
    op.create_index(op.f('ix_patch_patch_path'), 'patch', ['patch_path'], unique=False)
    op.create_index(op.f('ix_patch_patch_sequence_number'), 'patch', ['patch_sequence_number'], unique=False)
    op.create_index(op.f('ix_patch_state'), 'patch', ['state'], unique=False)
    op.create_table('patch_vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patch_sequence_number', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=48), nullable=False),
    sa.Column('commit_date', sa.DateTime(), nullable=False),
    sa.Column('patch_path', sa.String(length=512), nullable=False),
    sa.Column('patch_permalink_url', sa.String(length=1024), nullable=False),
    sa.Column('patch_target', sa.String(length=128), nullable=False),
    sa.Column('patch_hash', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('execution_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_vat_execution_date'), 'patch_vat', ['execution_date'], unique=False)
    op.create_index(op.f('ix_patch_vat_patch_path'), 'patch_vat', ['patch_path'], unique=False)
    op.create_index(op.f('ix_patch_vat_patch_sequence_number'), 'patch_vat', ['patch_sequence_number'], unique=False)
    op.create_index(op.f('ix_patch_vat_state'), 'patch_vat', ['state'], unique=False)
    op.create_table('population_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('f', 'm', 'x', 'u', 'o', 'all', name='gender'), nullable=False),
    sa.Column('age_range', sa.String(length=32), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin2_ref', 'gender', 'age_range')
    )
    op.create_index(op.f('ix_population_vat_admin1_code'), 'population_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_population_vat_admin1_name'), 'population_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_population_vat_admin2_code'), 'population_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_population_vat_admin2_name'), 'population_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_population_vat_location_code'), 'population_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_population_vat_location_name'), 'population_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_population_vat_max_age'), 'population_vat', ['max_age'], unique=False)
    op.create_index(op.f('ix_population_vat_min_age'), 'population_vat', ['min_age'], unique=False)
    op.create_index(op.f('ix_population_vat_population'), 'population_vat', ['population'], unique=False)
    op.create_index(op.f('ix_population_vat_reference_period_end'), 'population_vat', ['reference_period_end'], unique=False)
    op.create_index(op.f('ix_population_vat_reference_period_start'), 'population_vat', ['reference_period_start'], unique=False)
    op.create_table('poverty_rate_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('mpi', sa.Float(), nullable=False),
    sa.Column('headcount_ratio', sa.Float(), nullable=False),
    sa.Column('intensity_of_deprivation', sa.Float(), nullable=False),
    sa.Column('vulnerable_to_poverty', sa.Float(), nullable=False),
    sa.Column('in_severe_poverty', sa.Float(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('admin1_ref', 'admin1_name', 'reference_period_start')
    )
    op.create_index(op.f('ix_poverty_rate_vat_admin1_name'), 'poverty_rate_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_poverty_rate_vat_location_code'), 'poverty_rate_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_poverty_rate_vat_location_name'), 'poverty_rate_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_poverty_rate_vat_location_ref'), 'poverty_rate_vat', ['location_ref'], unique=False)
    op.create_index(op.f('ix_poverty_rate_vat_reference_period_end'), 'poverty_rate_vat', ['reference_period_end'], unique=False)
    op.create_table('refugees_vat',
    sa.Column('resource_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('origin_location_ref', sa.Integer(), nullable=False),
    sa.Column('asylum_location_ref', sa.Integer(), nullable=False),
    sa.Column('population_group', sa.Enum('REF', 'ROC', 'ASY', 'OIP', 'IDP', 'IOC', 'STA', 'OOC', 'HST', 'RET', 'RST', 'NAT', 'RDP', 'RRI', 'all', name='populationgroup'), nullable=False),
    sa.Column('gender', sa.Enum('f', 'm', 'x', 'u', 'o', 'all', name='gender'), nullable=False),
    sa.Column('age_range', sa.String(length=32), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('max_age', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('reference_period_start', sa.DateTime(), nullable=False),
    sa.Column('reference_period_end', sa.DateTime(), nullable=True),
    sa.Column('origin_location_code', sa.String(length=128), nullable=False),
    sa.Column('origin_location_name', sa.String(length=512), nullable=False),
    sa.Column('asylum_location_code', sa.String(length=128), nullable=False),
    sa.Column('asylum_location_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('origin_location_ref', 'asylum_location_ref', 'population_group', 'gender', 'age_range', 'reference_period_start')
    )
    op.create_index(op.f('ix_refugees_vat_asylum_location_code'), 'refugees_vat', ['asylum_location_code'], unique=False)
    op.create_index(op.f('ix_refugees_vat_asylum_location_name'), 'refugees_vat', ['asylum_location_name'], unique=False)
    op.create_index(op.f('ix_refugees_vat_max_age'), 'refugees_vat', ['max_age'], unique=False)
    op.create_index(op.f('ix_refugees_vat_min_age'), 'refugees_vat', ['min_age'], unique=False)
    op.create_index(op.f('ix_refugees_vat_origin_location_code'), 'refugees_vat', ['origin_location_code'], unique=False)
    op.create_index(op.f('ix_refugees_vat_origin_location_name'), 'refugees_vat', ['origin_location_name'], unique=False)
    op.create_index(op.f('ix_refugees_vat_population'), 'refugees_vat', ['population'], unique=False)
    op.create_index(op.f('ix_refugees_vat_reference_period_end'), 'refugees_vat', ['reference_period_end'], unique=False)
    op.create_table('resource_vat',
    sa.Column('hdx_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_hdx_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('is_hxl', sa.Boolean(), nullable=False),
    sa.Column('download_url', sa.String(length=1024), nullable=False),
    sa.Column('hapi_updated_date', sa.DateTime(), nullable=False),
    sa.Column('dataset_hdx_stub', sa.String(length=128), nullable=False),
    sa.Column('dataset_title', sa.String(length=1024), nullable=False),
    sa.Column('dataset_hdx_provider_stub', sa.String(length=128), nullable=False),
    sa.Column('dataset_hdx_provider_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('hdx_id')
    )
    op.create_index(op.f('ix_resource_vat_dataset_hdx_provider_name'), 'resource_vat', ['dataset_hdx_provider_name'], unique=False)
    op.create_index(op.f('ix_resource_vat_dataset_hdx_provider_stub'), 'resource_vat', ['dataset_hdx_provider_stub'], unique=False)
    op.create_index(op.f('ix_resource_vat_dataset_hdx_stub'), 'resource_vat', ['dataset_hdx_stub'], unique=False)
    op.create_table('sector_vat',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_sector_vat_name'), 'sector_vat', ['name'], unique=False)
    op.create_table('wfp_commodity_vat',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('category', sa.Enum('cereals and tubers', 'meat, fish and eggs', 'milk and dairy', 'miscellaneous food', 'non-food', 'oil and fats', 'pulses and nuts', 'vegetables and fruits', name='commoditycategory'), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_wfp_commodity_vat_category'), 'wfp_commodity_vat', ['category'], unique=False)
    op.create_index(op.f('ix_wfp_commodity_vat_name'), 'wfp_commodity_vat', ['name'], unique=False)
    op.create_table('wfp_market_vat',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('admin2_ref', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('location_code', sa.String(length=128), nullable=False),
    sa.Column('location_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_code', sa.String(length=128), nullable=False),
    sa.Column('admin1_name', sa.String(length=512), nullable=False),
    sa.Column('admin1_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('location_ref', sa.Integer(), nullable=False),
    sa.Column('admin2_code', sa.String(length=128), nullable=False),
    sa.Column('admin2_name', sa.String(length=512), nullable=False),
    sa.Column('admin2_is_unspecified', sa.Boolean(), nullable=False),
    sa.Column('admin1_ref', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_wfp_market_vat_admin1_code'), 'wfp_market_vat', ['admin1_code'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_admin1_name'), 'wfp_market_vat', ['admin1_name'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_admin2_code'), 'wfp_market_vat', ['admin2_code'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_admin2_name'), 'wfp_market_vat', ['admin2_name'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_lat'), 'wfp_market_vat', ['lat'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_location_code'), 'wfp_market_vat', ['location_code'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_location_name'), 'wfp_market_vat', ['location_name'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_lon'), 'wfp_market_vat', ['lon'], unique=False)
    op.create_index(op.f('ix_wfp_market_vat_name'), 'wfp_market_vat', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wfp_market_vat_name'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_lon'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_location_name'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_location_code'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_lat'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_admin2_name'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_admin2_code'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_admin1_name'), table_name='wfp_market_vat')
    op.drop_index(op.f('ix_wfp_market_vat_admin1_code'), table_name='wfp_market_vat')
    op.drop_table('wfp_market_vat')
    op.drop_index(op.f('ix_wfp_commodity_vat_name'), table_name='wfp_commodity_vat')
    op.drop_index(op.f('ix_wfp_commodity_vat_category'), table_name='wfp_commodity_vat')
    op.drop_table('wfp_commodity_vat')
    op.drop_index(op.f('ix_sector_vat_name'), table_name='sector_vat')
    op.drop_table('sector_vat')
    op.drop_index(op.f('ix_resource_vat_dataset_hdx_stub'), table_name='resource_vat')
    op.drop_index(op.f('ix_resource_vat_dataset_hdx_provider_stub'), table_name='resource_vat')
    op.drop_index(op.f('ix_resource_vat_dataset_hdx_provider_name'), table_name='resource_vat')
    op.drop_table('resource_vat')
    op.drop_index(op.f('ix_refugees_vat_reference_period_end'), table_name='refugees_vat')
    op.drop_index(op.f('ix_refugees_vat_population'), table_name='refugees_vat')
    op.drop_index(op.f('ix_refugees_vat_origin_location_name'), table_name='refugees_vat')
    op.drop_index(op.f('ix_refugees_vat_origin_location_code'), table_name='refugees_vat')
    op.drop_index(op.f('ix_refugees_vat_min_age'), table_name='refugees_vat')
    op.drop_index(op.f('ix_refugees_vat_max_age'), table_name='refugees_vat')
    op.drop_index(op.f('ix_refugees_vat_asylum_location_name'), table_name='refugees_vat')
    op.drop_index(op.f('ix_refugees_vat_asylum_location_code'), table_name='refugees_vat')
    op.drop_table('refugees_vat')
    op.drop_index(op.f('ix_poverty_rate_vat_reference_period_end'), table_name='poverty_rate_vat')
    op.drop_index(op.f('ix_poverty_rate_vat_location_ref'), table_name='poverty_rate_vat')
    op.drop_index(op.f('ix_poverty_rate_vat_location_name'), table_name='poverty_rate_vat')
    op.drop_index(op.f('ix_poverty_rate_vat_location_code'), table_name='poverty_rate_vat')
    op.drop_index(op.f('ix_poverty_rate_vat_admin1_name'), table_name='poverty_rate_vat')
    op.drop_table('poverty_rate_vat')
    op.drop_index(op.f('ix_population_vat_reference_period_start'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_reference_period_end'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_population'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_min_age'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_max_age'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_location_name'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_location_code'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_admin2_name'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_admin2_code'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_admin1_name'), table_name='population_vat')
    op.drop_index(op.f('ix_population_vat_admin1_code'), table_name='population_vat')
    op.drop_table('population_vat')
    op.drop_index(op.f('ix_patch_vat_state'), table_name='patch_vat')
    op.drop_index(op.f('ix_patch_vat_patch_sequence_number'), table_name='patch_vat')
    op.drop_index(op.f('ix_patch_vat_patch_path'), table_name='patch_vat')
    op.drop_index(op.f('ix_patch_vat_execution_date'), table_name='patch_vat')
    op.drop_table('patch_vat')
    op.drop_index(op.f('ix_patch_state'), table_name='patch')
    op.drop_index(op.f('ix_patch_patch_sequence_number'), table_name='patch')
    op.drop_index(op.f('ix_patch_patch_path'), table_name='patch')
    op.drop_index(op.f('ix_patch_execution_date'), table_name='patch')
    op.drop_table('patch')
    op.drop_index(op.f('ix_org_vat_org_type_description'), table_name='org_vat')
    op.drop_index(op.f('ix_org_vat_org_type_code'), table_name='org_vat')
    op.drop_table('org_vat')
    op.drop_index(op.f('ix_org_type_vat_description'), table_name='org_type_vat')
    op.drop_table('org_type_vat')
    op.drop_index(op.f('ix_operational_presence_vat_reference_period_end'), table_name='operational_presence_vat')
    op.drop_index(op.f('ix_operational_presence_vat_org_type_description'), table_name='operational_presence_vat')
    op.drop_index(op.f('ix_operational_presence_vat_location_name'), table_name='operational_presence_vat')
    op.drop_index(op.f('ix_operational_presence_vat_location_code'), table_name='operational_presence_vat')
    op.drop_index(op.f('ix_operational_presence_vat_admin2_name'), table_name='operational_presence_vat')
    op.drop_index(op.f('ix_operational_presence_vat_admin2_code'), table_name='operational_presence_vat')
    op.drop_index(op.f('ix_operational_presence_vat_admin1_name'), table_name='operational_presence_vat')
    op.drop_index(op.f('ix_operational_presence_vat_admin1_code'), table_name='operational_presence_vat')
    op.drop_table('operational_presence_vat')
    op.drop_index(op.f('ix_national_risk_vat_reference_period_end'), table_name='national_risk_vat')
    op.drop_index(op.f('ix_national_risk_vat_location_name'), table_name='national_risk_vat')
    op.drop_index(op.f('ix_national_risk_vat_location_code'), table_name='national_risk_vat')
    op.drop_table('national_risk_vat')
    op.drop_index(op.f('ix_location_vat_reference_period_start'), table_name='location_vat')
    op.drop_index(op.f('ix_location_vat_reference_period_end'), table_name='location_vat')
    op.drop_index(op.f('ix_location_vat_name'), table_name='location_vat')
    op.drop_index(op.f('ix_location_vat_code'), table_name='location_vat')
    op.drop_table('location_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_reference_period_end'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_min_age'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_max_age'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_location_name'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_location_code'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_admin2_name'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_admin2_code'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_admin1_name'), table_name='humanitarian_needs_vat')
    op.drop_index(op.f('ix_humanitarian_needs_vat_admin1_code'), table_name='humanitarian_needs_vat')
    op.drop_table('humanitarian_needs_vat')
    op.drop_index(op.f('ix_funding_vat_requirements_usd'), table_name='funding_vat')
    op.drop_index(op.f('ix_funding_vat_reference_period_start'), table_name='funding_vat')
    op.drop_index(op.f('ix_funding_vat_location_name'), table_name='funding_vat')
    op.drop_index(op.f('ix_funding_vat_location_code'), table_name='funding_vat')
    op.drop_index(op.f('ix_funding_vat_funding_usd'), table_name='funding_vat')
    op.drop_index(op.f('ix_funding_vat_funding_pct'), table_name='funding_vat')
    op.drop_table('funding_vat')
    op.drop_index(op.f('ix_food_security_vat_reference_period_end'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_population_in_phase'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_population_fraction_in_phase'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_location_name'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_location_code'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_admin2_name'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_admin2_code'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_admin1_name'), table_name='food_security_vat')
    op.drop_index(op.f('ix_food_security_vat_admin1_code'), table_name='food_security_vat')
    op.drop_table('food_security_vat')
    op.drop_index(op.f('ix_food_price_vat_reference_period_end'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_market_name'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_lon'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_location_name'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_location_code'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_lat'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_currency_code'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_commodity_name'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_admin2_name'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_admin2_code'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_admin1_name'), table_name='food_price_vat')
    op.drop_index(op.f('ix_food_price_vat_admin1_code'), table_name='food_price_vat')
    op.drop_table('food_price_vat')
    op.drop_index(op.f('ix_dataset_vat_hdx_stub'), table_name='dataset_vat')
    op.drop_index(op.f('ix_dataset_vat_hdx_provider_stub'), table_name='dataset_vat')
    op.drop_index(op.f('ix_dataset_vat_hdx_provider_name'), table_name='dataset_vat')
    op.drop_table('dataset_vat')
    op.drop_index(op.f('ix_currency_vat_name'), table_name='currency_vat')
    op.drop_table('currency_vat')
    op.drop_index(op.f('ix_conflict_event_vat_reference_period_end'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_location_name'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_location_code'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_fatalities'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_events'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_admin2_name'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_admin2_code'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_admin1_name'), table_name='conflict_event_vat')
    op.drop_index(op.f('ix_conflict_event_vat_admin1_code'), table_name='conflict_event_vat')
    op.drop_table('conflict_event_vat')
    op.drop_index(op.f('ix_admin2_vat_reference_period_start'), table_name='admin2_vat')
    op.drop_index(op.f('ix_admin2_vat_reference_period_end'), table_name='admin2_vat')
    op.drop_index(op.f('ix_admin2_vat_name'), table_name='admin2_vat')
    op.drop_index(op.f('ix_admin2_vat_location_name'), table_name='admin2_vat')
    op.drop_index(op.f('ix_admin2_vat_location_code'), table_name='admin2_vat')
    op.drop_index(op.f('ix_admin2_vat_code'), table_name='admin2_vat')
    op.drop_table('admin2_vat')
    op.drop_index(op.f('ix_admin1_vat_reference_period_start'), table_name='admin1_vat')
    op.drop_index(op.f('ix_admin1_vat_reference_period_end'), table_name='admin1_vat')
    op.drop_index(op.f('ix_admin1_vat_name'), table_name='admin1_vat')
    op.drop_index(op.f('ix_admin1_vat_location_name'), table_name='admin1_vat')
    op.drop_index(op.f('ix_admin1_vat_location_code'), table_name='admin1_vat')
    op.drop_index(op.f('ix_admin1_vat_code'), table_name='admin1_vat')
    op.drop_table('admin1_vat')
    # ### end Alembic commands ###
