services:

  hwa:
    image: public.ecr.aws/unocha/hdx-hapi-write-app:${HWA_IMAGE_TAG:-main}
    # build:
    #   context: ./..
    #   dockerfile: Dockerfile
    hostname: hapi
    working_dir: /srv/hwa
    environment:
      HAPI_DB_NAME: ${HAPI_DB_NAME:-hapi}
      HAPI_DB_USER: ${HAPI_DB_USER:-hapi}
      HAPI_DB_PASS: ${HAPI_DB_PASS:-hapi}
      HAPI_DB_HOST: ${HAPI_DB_NAME:-db}
      HAPI_DB_PORT: ${HAPI_DB_PORT:-5432}
      HWA_PATCH_TOKEN: ${HWA_PATCH_TOKEN}
    volumes:
      - "./..:/srv/hwa"
    entrypoint: tail -f /dev/null
    networks:
      - hapi

  db:
    image: postgres:15.4-alpine3.18
    hostname: db
    ports:
      - "127.0.0.1:45432:5432"
    volumes:
      - "${BASEDIR:-./postgres-data}/dbs/hwa-psql:/var/lib/pgsql"
    environment:
      PGDATA: /var/lib/pgsql
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    networks:
      - hapi
    profiles:
      - testing

networks:
  hapi:
    name: hapi_stack_hapi
    external: true
      
