name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: They are the same.
        run: sudo ln -sf /usr/libexec/docker/cli-plugins/docker-compose /usr/bin/docker-compose

      - name: Build the docker-compose stack
        run: |
          docker network create -d bridge hapi_stack_hapi
          cd docker
          docker-compose --profile=testing up -d
        env:
          HWA_PATCH_TOKEN: ${{ secrets.HWA_PATCH_TOKEN }}

      - name: Install requirements
        run: |
          cd docker
          docker-compose exec -T hwa sh -c "apk add git"
          docker-compose exec -T hwa sh -c "pip install --upgrade -r requirements.txt"
          docker-compose exec -T hwa sh -c "pip install --upgrade -r dev-requirements.txt"

      - name: Setup database
        run: |
          ./initialize_test_db.sh

      - name: Test with pytest
        run: |
          cd docker
          docker-compose exec -T hwa sh -c "pytest --log-level=INFO --cov=. --cov-report term --cov-report xml:coverage.xml"

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
